# Generated by Django 5.2.7 on 2025-11-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in-progress', 'In Progress'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('newsletter', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-date'],
            },
        ),
    ]
